services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    environment:
      MONGODB_URI: "mongodb://192.168.50.116:27017"
      RESUME_CUSTOMIZER_DB: "resume_customizer"
      RESUME_SCORER_DB: "resume_scorer"
